# Generated by Django 4.2.7 on 2024-09-22 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='birthday_date',
            field=models.IntegerField(blank=True, default='2004', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, default='ФИО абитуриента', null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='budget_passing_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='budget_place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='paid_place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 15, 37, 3, 314140, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
