# Generated by Django 4.2.7 on 2024-09-22 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applicant_birthday_date_applicant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 15, 39, 13, 367418, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
