# Generated by Django 4.2.7 on 2024-09-22 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_applicant_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birthday_date',
            field=models.IntegerField(blank=True, default='Не указан', null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 15, 40, 56, 559223, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, default='Не указано', null=True),
        ),
    ]
