# Generated by Django 4.2.7 on 2024-09-22 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_applicant_birthday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birthday_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 15, 42, 36, 140412, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
