# Generated by Django 4.2.7 on 2024-09-22 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_applicant_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 15, 46, 43, 397999, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
